package com.aya.digital.core.util.requestcodes

object RequestCodes {
    const val INSURANCE_LIST_REQUEST_CODE = "INSURANCE_LIST_REQUEST_CODE"
    const val SPECIALITIES_LIST_REQUEST_CODE = "SPECIALITIES_LIST_REQUEST_CODE"
    const val LOCATIONS_LIST_REQUEST_CODE = "LOCATIONS_LIST_REQUEST_CODE"
    const val LANGUAGES_LIST_REQUEST_CODE = "LANGUAGES_LIST_REQUEST_CODE"
    const val CODE_INPUT_REQUEST_CODE_EMAIL = "CODE_INPUT_REQUEST_CODE_EMAIL"
    const val CODE_INPUT_REQUEST_CODE_PHONE = "CODE_INPUT_REQUEST_CODE_PHONE"
    const val RESTORE_PASSWORD_REQUEST_CODE = "CODE_INPUT_REQUEST_CODE"
    const val VIEW_PROFILE_REQUEST_CODE = "VIEW_PROFILE_REQUEST_CODE"
    const val EDIT_PROFILE_REQUEST_CODE = "EDIT_PROFILE_REQUEST_CODE"
    const val ADD_INSURANCE_REQUEST_CODE = "ADD_INSURANCE_REQUEST_CODE"
    const val EDIT_INSURANCE_REQUEST_CODE = "EDIT_INSURANCE_REQUEST_CODE"
    const val CHANGE_EMAIL_REQUEST_CODE = "CHANGE_EMAIL_REQUEST_CODE"
    const val CHANGE_PHONE_REQUEST_CODE = "CHANGE_PHONE_REQUEST_CODE"
    const val CHANGE_SECURITY_INFO_REQUEST_CODE = "CHANGE_SECURITY_INFO_REQUEST_CODE"
    const val CHANGE_PASSWORD_REQUEST_CODE = "CHANGE_PASSWORD_REQUEST_CODE"
    const val CREATE_APPOINTMENT_REQUEST_CODE = "CREATE_APPOINTMENT_REQUEST_CODE"
    const val SUCCESS_APPOINTMENT_REQUEST_CODE = "SUCCESS_APPOINTMENT_REQUEST_CODE"
    const val APPOINTMENTS_FOR_DATE_REQUEST_CODE = "APPOINTMENTS_FOR_DATE_REQUEST_CODE"


}