FROM ubuntu:22.04

RUN apt-get --quiet update --yes && apt-get --quiet install --yes wget tar unzip lib32stdc++6-x32-cross libbz2-1.0 git curl autoconf bison build-essential \
                                                                                                                            libssl-dev libyaml-dev libreadline6-dev zlib1g-dev \
                                                                                                                           libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev \
RUN curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
RUN echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(rbenv init -)"' >> ~/.bashrc
SHELL ["/bin/bash", "-c", "source ~/.bashrc"]
RUN rbenv install 3.2.0
COPY Gemfile ./Gemfile
RUN echo ruby -version
RUN gem update
RUN gem install bundler
RUN bundle install
RUN bundle update
RUN apt-get install -y openjdk-17-jdk



ENV ANDROID_TOOLS="9477386_latest"
ENV ANDROID_API_LEVEL="33"
ENV ANDROID_BUILD_TOOLS="33.0.0"
ENV GRADLE_VERSION="8.0"

# Download commandlinetools
RUN wget --quiet --output-document=android-sdk.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_TOOLS}.zip" \
      && mkdir -p /root/.android \
      && touch /root/.android/repositories.cfg \
      && mkdir -p /Android/cmdline-tools \
      && unzip -d /Android/cmdline-tools android-sdk.zip >/dev/null \
      && mv /Android/cmdline-tools/cmdline-tools/ /Android/cmdline-tools/latest/ \
      && rm -rf android-sdk.zip

RUN yes | /Android/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-${ANDROID_API_LEVEL}"
RUN yes | /Android/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
RUN yes | /Android/cmdline-tools/latest/bin/sdkmanager --install "build-tools;${ANDROID_BUILD_TOOLS}"
RUN yes | /Android/cmdline-tools/latest/bin/sdkmanager --licenses

ENV ANDROID_HOME=/Android/
ENV PATH="$PATH:/Android/cmdline-tools/latest/bin"
ENV PATH="$PATH:/Android/platform-tools"

# Download Gradle
RUN mkdir /opt/gradle \
      && wget -q "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
      && unzip -d /opt/gradle "gradle-${GRADLE_VERSION}-bin.zip" \
      && rm -rf "gradle-${GRADLE_VERSION}-bin.zip"



ENV PATH="$PATH:/opt/gradle/gradle-${GRADLE_VERSION}/bin"

RUN fastline debug

